name: 'Download Files To Workspace'
description: 'Download files from the internet into the workspace.'
author: 'SettingDust'
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  file-url:
    description: 'URL of the files to download. Split with line breaks'
    required: true
  location:
    description: 'Path to download the files'
    required: false
    default: "."
outputs:
  file-path:
    description: 'The full path to the downloaded files. Split with line breaks'
runs:
  using: 'node16'
  main: 'dist/index.js'
