name: Workflow To Test Action

on: [push]

jobs:
  action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    name: Test Action - ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Simple test to download a file
        uses: ./
        id: download-poetry-simple
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-simple.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile('get-poetry.py'))"
      - name: Test action output path is correct
        run: python -c "exit(not '${{ steps.download-poetry-simple.outputs.file-path }}' == 'get-poetry.py')"
      - run: ls && rm ${{ steps.download-poetry-simple.outputs.file-path }} && ls

      - name: Test to download a file with a different filename
        uses: ./
        id: download-poetry-name
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          file-name: 'new_name.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-name.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile('new_name.py'))"
      - name: Test action output path is correct
        run: python -c "exit(not '${{ steps.download-poetry-name.outputs.file-path }}' == 'new_name.py')"
      - run: ls && rm ${{ steps.download-poetry-name.outputs.file-path }} && ls

      - name: Test to download a file to a different path
        uses: ./
        id: download-poetry-location
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: 'new_folder'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-location.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile('new_folder/get-poetry.py'))"
      - name: Test action output path is correct
        run: python -c "import os; exit(not '${{ steps.download-poetry-location.outputs.file-path }}' == os.path.normpath('new_folder/get-poetry.py'))"
      - run: ls new_folder && rm -r new_folder

      - name: Test to download a file to a relative path
        uses: ./
        id: download-poetry-relative
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: '../'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-relative.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile('../get-poetry.py'))"
      - name: Test action output path is correct
        run: python -c "import os; exit(not '${{ steps.download-poetry-relative.outputs.file-path }}' == os.path.normpath('../get-poetry.py'))"
      - run: ls ../ && rm ${{ steps.download-poetry-relative.outputs.file-path }} && ls ../

      - name: Test to download a file to an absolute path
        uses: ./
        id: download-poetry-absolute
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: '${{ github.workspace }}/a_folder'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-absolute.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile(r'${{ github.workspace }}/a_folder/get-poetry.py'))"
      - name: Test action output path is correct
        run: python -c "import os; exit(not os.path.normpath(r'${{ steps.download-poetry-absolute.outputs.file-path }}') == os.path.normpath(r'${{ github.workspace }}/a_folder/get-poetry.py'))"
      - run: ls ${{ github.workspace }}/a_folder && rm -r ${{ github.workspace }}/a_folder

      - name: Test to download a file to a different filename and path
        uses: ./
        id: download-poetry-both
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: 'different_folder'
          file-name: 'new_name.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-both.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os; exit(not os.path.isfile('different_folder/new_name.py'))"
