name: Workflow To Test Action

on: [push]

jobs:
  action-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2019]
      fail-fast: false
    name: Test Action - ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Simple test to download a file
        uses: ./
        id: download-poetry-simple
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-simple.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os, sys; sys.exit(not os.path.isfile('get-poetry.py'))"
      - run: ls && rm ${{ steps.download-poetry-simple.outputs.file-path }} && ls

      - name: Test to download a file with a different filename
        uses: ./
        id: download-poetry-name
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          file-name: 'new_name.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-name.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os, sys; sys.exit(not os.path.isfile('new_name.py'))"
      - run: ls && rm ${{ steps.download-poetry-name.outputs.file-path }} && ls

      - name: Test to download a file to a different path
        uses: ./
        id: download-poetry-location
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: 'new_folder'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-location.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os, sys; sys.exit(not os.path.isfile('new_folder/get-poetry.py'))"
      - run: ls new_folder && rm ${{ steps.download-poetry-location.outputs.file-path }} && ls new_folder

      - name: Test to download a file to a relative path
        uses: ./
        id: download-poetry-relative
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: '../'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-relative.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os, sys; sys.exit(not os.path.isfile('../get-poetry.py'))"
      - run: ls ../ && rm ${{ steps.download-poetry-relative.outputs.file-path }} && ls ../

      - name: Test to download a file to a different filename and path
        uses: ./
        id: download-poetry-both
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          location: 'new_folder'
          file-name: 'new_name.py'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-both.outputs.file-path }}"
      - name: Test file exists
        run: python -c "import os, sys; sys.exit(not os.path.isfile('new_folder/new_name.py'))"
      - run: ls new_folder && rm ${{ steps.download-poetry-both.outputs.file-path }} && ls new_folder
